In [1]:
import torch

In [2]:
print(torch.__version__)

2.7.1


In [3]:
if torch.cuda.is_available():
  print(torch.cuda.get_device_name(0))
  print('cuda')

In [4]:
a = torch.empty(2,3)

In [6]:
a, type(a)

(tensor([[0., 0., 0.],
         [0., 0., 0.]]),
 torch.Tensor)

In [8]:
a.fill_(1)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [9]:
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [10]:
torch.rand(3,4)

tensor([[0.0984, 0.3230, 0.0187, 0.2322],
        [0.1061, 0.7115, 0.8082, 0.9480],
        [0.6382, 0.4556, 0.0148, 0.3432]])

In [11]:
torch.rand(3,4)

tensor([[0.2885, 0.8234, 0.4748, 0.2576],
        [0.6830, 0.9596, 0.6920, 0.9577],
        [0.7800, 0.7280, 0.0584, 0.3753]])

In [12]:
torch.rand(3,4)

tensor([[0.4230, 0.4807, 0.9671, 0.6336],
        [0.1558, 0.8210, 0.2399, 0.5868],
        [0.5428, 0.1695, 0.4419, 0.5448]])

In [13]:
torch.manual_seed(10)
torch.rand(3,4)

tensor([[0.4581, 0.4829, 0.3125, 0.6150],
        [0.2139, 0.4118, 0.6938, 0.9693],
        [0.6178, 0.3304, 0.5479, 0.4440]])

In [14]:
torch.manual_seed(10)
torch.rand(3,4)

tensor([[0.4581, 0.4829, 0.3125, 0.6150],
        [0.2139, 0.4118, 0.6938, 0.9693],
        [0.6178, 0.3304, 0.5479, 0.4440]])

In [15]:
torch.manual_seed(11)
torch.rand(3,4)

tensor([[0.1490, 0.4866, 0.9857, 0.1684],
        [0.5839, 0.6936, 0.5831, 0.1284],
        [0.5721, 0.9248, 0.2693, 0.7825]])

In [16]:
torch.manual_seed(11)
torch.rand(3,4)

tensor([[0.1490, 0.4866, 0.9857, 0.1684],
        [0.5839, 0.6936, 0.5831, 0.1284],
        [0.5721, 0.9248, 0.2693, 0.7825]])

In [17]:
torch.tensor([[1,2,3],[3,4,5]])

tensor([[1, 2, 3],
        [3, 4, 5]])

In [20]:
torch.arange(10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
torch.arange(3, 10)

tensor([3, 4, 5, 6, 7, 8, 9])

In [22]:
torch.arange(1, 10, 2)

tensor([1, 3, 5, 7, 9])

In [23]:
torch.linspace(0,20,5)

tensor([ 0.,  5., 10., 15., 20.])

In [24]:
torch.eye(4)

tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])

In [25]:
torch.full((2,3),5)

tensor([[5, 5, 5],
        [5, 5, 5]])

In [26]:
x = torch.tensor([[1,2,3],[3,4,5]])
x.shape

torch.Size([2, 3])

In [27]:
torch.empty_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [28]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [29]:
torch.rand_like(x,dtype=torch.float32)

tensor([[0.2719, 0.4632, 0.7671],
        [0.5024, 0.1025, 0.7600]])

In [30]:
x

tensor([[1, 2, 3],
        [3, 4, 5]])

In [31]:
x+2

tensor([[3, 4, 5],
        [5, 6, 7]])

In [32]:
x-2

tensor([[-1,  0,  1],
        [ 1,  2,  3]])

In [33]:
x*3

tensor([[ 3,  6,  9],
        [ 9, 12, 15]])

In [34]:
x/3

tensor([[0.3333, 0.6667, 1.0000],
        [1.0000, 1.3333, 1.6667]])

In [35]:
c = torch.tensor([1, -2, 3, -4])

In [36]:
torch.abs(c)

tensor([1, 2, 3, 4])

In [37]:
torch.neg(c)

tensor([-1,  2, -3,  4])

In [38]:
d = torch.tensor([1.9, 2.3, 3.7, 4.4])

In [39]:
torch.round(d)

tensor([2., 2., 4., 4.])

In [40]:
torch.floor(d)

tensor([1., 2., 3., 4.])

In [41]:
torch.ceil(d)

tensor([2., 3., 4., 5.])

In [42]:
e=torch.randint(size=(3,4),low=0,high=10,dtype=torch.float32)

In [43]:
e

tensor([[8., 1., 8., 2.],
        [8., 9., 2., 3.],
        [1., 7., 0., 1.]])

In [44]:
torch.sum(e)

tensor(50.)

In [45]:
torch.sum(e, dim=0)

tensor([17., 17., 10.,  6.])

In [46]:
torch.sum(e, dim=1)

tensor([19., 22.,  9.])

In [47]:
torch.mean(e, dim=1)

tensor([4.7500, 5.5000, 2.2500])

In [48]:
torch.mean(e)

tensor(4.1667)

In [49]:
torch.min(e)

tensor(0.)

In [50]:
torch.argmax(e)

tensor(5)

In [51]:
torch.argmin(e)

tensor(10)

In [52]:
f = torch.randint(size=(2,3), low=0, high=10)
g = torch.randint(size=(3,2), low=0, high=10)

In [53]:
f

tensor([[5, 6, 0],
        [5, 3, 0]])

In [54]:
g

tensor([[3, 4],
        [0, 6],
        [9, 1]])

In [55]:
torch.matmul(f,g)

tensor([[15, 56],
        [15, 38]])

In [56]:
vector1 = torch.tensor([1, 2])
vector2 = torch.tensor([3, 4])

In [57]:
vector1

tensor([1, 2])

In [58]:
vector2

tensor([3, 4])

In [59]:
torch.dot(vector1,vector2)

tensor(11)

In [60]:
f

tensor([[5, 6, 0],
        [5, 3, 0]])

In [61]:
torch.transpose(f,0,1)

tensor([[5, 5],
        [6, 3],
        [0, 0]])

In [62]:
h = torch.randint(size=(3,3), low=0, high=10, dtype=torch.float32)

In [63]:
h

tensor([[8., 7., 9.],
        [8., 5., 1.],
        [2., 5., 7.]])

In [64]:
torch.inverse(h)

tensor([[ 0.2273, -0.0303, -0.2879],
        [-0.4091,  0.2879,  0.4848],
        [ 0.2273, -0.1970, -0.1212]])

In [65]:
torch.log(h)

tensor([[2.0794, 1.9459, 2.1972],
        [2.0794, 1.6094, 0.0000],
        [0.6931, 1.6094, 1.9459]])

In [66]:
torch.exp(h)

tensor([[2.9810e+03, 1.0966e+03, 8.1031e+03],
        [2.9810e+03, 1.4841e+02, 2.7183e+00],
        [7.3891e+00, 1.4841e+02, 1.0966e+03]])

In [67]:
torch.softmax(h,0)

tensor([[4.9938e-01, 7.8699e-01, 8.8054e-01],
        [4.9938e-01, 1.0651e-01, 2.9539e-04],
        [1.2378e-03, 1.0651e-01, 1.1917e-01]])