In [1]:
import torch

In [2]:
print(torch.__version__)

2.7.1


In [3]:
if torch.cuda.is_available():
  print(torch.cuda.get_device_name(0))
  print('cuda')

## Concept of autograd
### NN Module of Python

In [5]:
def dy_dx(x):
    return 2*x

In [6]:
dy_dx(4)

8

In [10]:
x = torch.tensor(3., requires_grad=True)
x

tensor(3., requires_grad=True)

In [11]:
y = x**2

In [12]:
y

tensor(9., grad_fn=<PowBackward0>)

In [13]:
y.backward()

In [15]:
x.grad

tensor(6.)

In [16]:
import math

def dy_dx(x):
    return 2*x*math.cos(x**2)

In [17]:
dy_dx(3)

-5.466781571308061

In [18]:
dy_dx(5)

9.912028118634735

In [19]:
x = torch.tensor(3., requires_grad=True)

In [20]:
y = x**2
y

tensor(9., grad_fn=<PowBackward0>)

In [21]:
z = torch.sin(y)
z

tensor(0.4121, grad_fn=<SinBackward0>)

In [22]:
z.backward()

In [23]:
x.grad

tensor(-5.4668)

In [25]:
y.grad

/var/folders/89/ssy6ymh96j9f2f7kcyp_sljh0000gn/T/ipykernel_7990/486760323.py:1: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the .grad field to be populated for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more informations. (Triggered internally at /Users/runner/work/pytorch/pytorch/pytorch/build/aten/src/ATen/core/TensorBody.h:494.)
  y.grad


In [26]:
import torch.nn as nn

In [43]:
class Model(nn.Module):

    def __init__(self, new_features):
        super().__init__()
        self.linear = nn.Linear(new_features, 1)
        self.sigmoid = nn.Sigmoid()

    def forward(self, features):
        out = self.linear(features)
        out = self.sigmoid(out)

        return out

In [44]:
features = torch.rand(10,5)
features, features.shape, features.shape[1]

(tensor([[0.7915, 0.9957, 0.2731, 0.1807, 0.5826],
         [0.7416, 0.5014, 0.1317, 0.6642, 0.0212],
         [0.0103, 0.6571, 0.8825, 0.8169, 0.7897],
         [0.9219, 0.4274, 0.6011, 0.6197, 0.8087],
         [0.0210, 0.0397, 0.8870, 0.1403, 0.4987],
         [0.4861, 0.4932, 0.2987, 0.5663, 0.5191],
         [0.1625, 0.7026, 0.3782, 0.2441, 0.6548],
         [0.2325, 0.0978, 0.6753, 0.7772, 0.5415],
         [0.1322, 0.3831, 0.1028, 0.8598, 0.8862],
         [0.7997, 0.7117, 0.3011, 0.9206, 0.5047]]),
 torch.Size([10, 5]),
 5)

In [45]:
model = Model(features.shape[1])

In [46]:
model(features)

tensor([[0.6311],
        [0.5675],
        [0.6084],
        [0.5693],
        [0.6045],
        [0.5650],
        [0.6068],
        [0.5481],
        [0.4989],
        [0.5648]], grad_fn=<SigmoidBackward0>)

In [47]:
model.forward(features)

tensor([[0.6311],
        [0.5675],
        [0.6084],
        [0.5693],
        [0.6045],
        [0.5650],
        [0.6068],
        [0.5481],
        [0.4989],
        [0.5648]], grad_fn=<SigmoidBackward0>)

In [48]:
model.linear.weight

Parameter containing:
tensor([[-0.0068,  0.4020,  0.3900, -0.2544, -0.1985]], requires_grad=True)

In [49]:
model.linear.bias

Parameter containing:
tensor([0.1971], requires_grad=True)

In [55]:
class Model(nn.Module):
    def __init__(self, new_features):
        super().__init__()
        self.linear1 = nn.Linear(new_features, 3)
        self.relu = nn.ReLU()
        self.linear2 = nn.Linear(3, 1)
        self.sigmoid = nn.Sigmoid()
    def forward(self, features):
        out = self.linear1(features)
        out = self.relu(out)
        out = self.linear2(out)
        out = self.sigmoid(out)
        return out

In [56]:
data = torch.rand(10,5)
data

tensor([[0.5545, 0.5797, 0.9005, 0.3952, 0.7753],
        [0.9572, 0.6444, 0.1616, 0.6735, 0.8307],
        [0.4459, 0.3230, 0.8104, 0.5956, 0.7751],
        [0.2930, 0.1088, 0.2672, 0.2694, 0.0572],
        [0.8292, 0.3457, 0.0910, 0.9811, 0.6688],
        [0.3230, 0.3333, 0.5363, 0.4705, 0.2828],
        [0.6237, 0.6928, 0.7195, 0.8398, 0.9560],
        [0.2537, 0.3819, 0.4983, 0.0746, 0.6866],
        [0.1569, 0.4556, 0.9451, 0.4749, 0.6934],
        [0.1779, 0.1150, 0.7919, 0.5769, 0.9635]])

In [57]:
data.shape

torch.Size([10, 5])

In [58]:
data.shape[1]

5

In [59]:
model = Model(data.shape[1])

In [60]:
model(data)

tensor([[0.6079],
        [0.6106],
        [0.6051],
        [0.5898],
        [0.6010],
        [0.5895],
        [0.6027],
        [0.6073],
        [0.5961],
        [0.6080]], grad_fn=<SigmoidBackward0>)

In [61]:
model.linear1.weight

Parameter containing:
tensor([[ 0.2797, -0.1978,  0.0277, -0.2434,  0.3247],
        [-0.3095, -0.4086, -0.0305,  0.2811, -0.3620],
        [-0.2159, -0.0887, -0.2940, -0.3478,  0.1385]], requires_grad=True)

In [62]:
model.linear1.bias

Parameter containing:
tensor([ 7.3176e-02, -3.4483e-01,  1.8979e-04], requires_grad=True)

In [63]:
model.linear2.weight

Parameter containing:
tensor([[0.3758, 0.0923, 0.1659]], requires_grad=True)

In [64]:
model.linear2.bias

Parameter containing:
tensor([0.3280], requires_grad=True)

In [65]:
class Model(nn.Module):
    def __init__(self, num_features):
        super().__init__()
        self.network = nn.Sequential(
            nn.Linear(num_features, 3),
            nn.ReLU(),
            nn.Linear(3, 1),
            nn.Sigmoid()
        )
    def forward(self, features):
        out = self.network(features)
        return out

In [67]:
data = torch.rand(10,5)
data

tensor([[0.0416, 0.7512, 0.7232, 0.1355, 0.8984],
        [0.6026, 0.6980, 0.8657, 0.6511, 0.9027],
        [0.8724, 0.1878, 0.4705, 0.2993, 0.3116],
        [0.3427, 0.9993, 0.6652, 0.1795, 0.3158],
        [0.3200, 0.8304, 0.2519, 0.1158, 0.3959],
        [0.3805, 0.8778, 0.8939, 0.7039, 0.1768],
        [0.0665, 0.4424, 0.8268, 0.6295, 0.2843],
        [0.0536, 0.3157, 0.3867, 0.6518, 0.9850],
        [0.7139, 0.6522, 0.0127, 0.7063, 0.8943],
        [0.2426, 0.6785, 0.2321, 0.2841, 0.7577]])

In [68]:
model = Model(data.shape[1])
model

Model(
  (network): Sequential(
    (0): Linear(in_features=5, out_features=3, bias=True)
    (1): ReLU()
    (2): Linear(in_features=3, out_features=1, bias=True)
    (3): Sigmoid()
  )
)

In [69]:
model(data)

tensor([[0.5196],
        [0.5131],
        [0.5290],
        [0.5213],
        [0.5262],
        [0.5230],
        [0.5272],
        [0.5017],
        [0.4847],
        [0.5135]], grad_fn=<SigmoidBackward0>)

In [70]:
model.forward(data)

tensor([[0.5196],
        [0.5131],
        [0.5290],
        [0.5213],
        [0.5262],
        [0.5230],
        [0.5272],
        [0.5017],
        [0.4847],
        [0.5135]], grad_fn=<SigmoidBackward0>)

In [71]:
from torchinfo import summary

In [72]:
summary(model)

Layer (type:depth-idx)                   Param #
Model                                    --
├─Sequential: 1-1                        --
│    └─Linear: 2-1                       18
│    └─ReLU: 2-2                         --
│    └─Linear: 2-3                       4
│    └─Sigmoid: 2-4                      --
Total params: 22
Trainable params: 22
Non-trainable params: 0

In [73]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [74]:
data = pd.read_csv("https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv")
data

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0      842302         M        17.99         10.38          122.80     1001.0   
1      842517         M        20.57         17.77          132.90     1326.0   
2    84300903         M        19.69         21.25          130.00     1203.0   
3    84348301         M        11.42         20.38           77.58      386.1   
4    84358402         M        20.29         14.34          135.10     1297.0   
..        ...       ...          ...           ...             ...        ...   
564    926424         M        21.56         22.39          142.00     1479.0   
565    926682         M        20.13         28.25          131.20     1261.0   
566    926954         M        16.60         28.08          108.30      858.1   
567    927241         M        20.60         29.33          140.10     1265.0   
568     92751         B         7.76         24.54           47.92      181.0   

     smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0            0.11840           0.27760         0.30010              0.14710   
1            0.08474           0.07864         0.08690              0.07017   
2            0.10960           0.15990         0.19740              0.12790   
3            0.14250           0.28390         0.24140              0.10520   
4            0.10030           0.13280         0.19800              0.10430   
..               ...               ...             ...                  ...   
564          0.11100           0.11590         0.24390              0.13890   
565          0.09780           0.10340         0.14400              0.09791   
566          0.08455           0.10230         0.09251              0.05302   
567          0.11780           0.27700         0.35140              0.15200   
568          0.05263           0.04362         0.00000              0.00000   

     ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0    ...          17.33           184.60      2019.0           0.16220   
1    ...          23.41           158.80      1956.0           0.12380   
2    ...          25.53           152.50      1709.0           0.14440   
3    ...          26.50            98.87       567.7           0.20980   
4    ...          16.67           152.20      1575.0           0.13740   
..   ...            ...              ...         ...               ...   
564  ...          26.40           166.10      2027.0           0.14100   
565  ...          38.25           155.00      1731.0           0.11660   
566  ...          34.12           126.70      1124.0           0.11390   
567  ...          39.42           184.60      1821.0           0.16500   
568  ...          30.37            59.16       268.6           0.08996   

     compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0              0.66560           0.7119                0.2654          0.4601   
1              0.18660           0.2416                0.1860          0.2750   
2              0.42450           0.4504                0.2430          0.3613   
3              0.86630           0.6869                0.2575          0.6638   
4              0.20500           0.4000                0.1625          0.2364   
..                 ...              ...                   ...             ...   
564            0.21130           0.4107                0.2216          0.2060   
565            0.19220           0.3215                0.1628          0.2572   
566            0.30940           0.3403                0.1418          0.2218   
567            0.86810           0.9387                0.2650          0.4087   
568            0.06444           0.0000                0.0000          0.2871   

     fractal_dimension_worst  Unnamed: 32  
0                    0.11890          NaN  
1                    0.08902          NaN  
2                    0.08758          NaN  
3                    0.17300          NaN  
4      

In [75]:
data.columns

Index(['id', 'diagnosis', 'radius_mean', 'texture_mean', 'perimeter_mean',
       'area_mean', 'smoothness_mean', 'compactness_mean', 'concavity_mean',
       'concave points_mean', 'symmetry_mean', 'fractal_dimension_mean',
       'radius_se', 'texture_se', 'perimeter_se', 'area_se', 'smoothness_se',
       'compactness_se', 'concavity_se', 'concave points_se', 'symmetry_se',
       'fractal_dimension_se', 'radius_worst', 'texture_worst',
       'perimeter_worst', 'area_worst', 'smoothness_worst',
       'compactness_worst', 'concavity_worst', 'concave points_worst',
       'symmetry_worst', 'fractal_dimension_worst', 'Unnamed: 32'],
      dtype='object')

In [79]:
data.drop(['id', 'Unnamed: 32'], axis = 1, inplace = True)

In [80]:
data

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0           M        17.99         10.38          122.80     1001.0   
1           M        20.57         17.77          132.90     1326.0   
2           M        19.69         21.25          130.00     1203.0   
3           M        11.42         20.38           77.58      386.1   
4           M        20.29         14.34          135.10     1297.0   
..        ...          ...           ...             ...        ...   
564         M        21.56         22.39          142.00     1479.0   
565         M        20.13         28.25          131.20     1261.0   
566         M        16.60         28.08          108.30      858.1   
567         M        20.60         29.33          140.10     1265.0   
568         B         7.76         24.54           47.92      181.0   

     smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0            0.11840           0.27760         0.30010              0.14710   
1            0.08474           0.07864         0.08690              0.07017   
2            0.10960           0.15990         0.19740              0.12790   
3            0.14250           0.28390         0.24140              0.10520   
4            0.10030           0.13280         0.19800              0.10430   
..               ...               ...             ...                  ...   
564          0.11100           0.11590         0.24390              0.13890   
565          0.09780           0.10340         0.14400              0.09791   
566          0.08455           0.10230         0.09251              0.05302   
567          0.11780           0.27700         0.35140              0.15200   
568          0.05263           0.04362         0.00000              0.00000   

     symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0           0.2419  ...        25.380          17.33           184.60   
1           0.1812  ...        24.990          23.41           158.80   
2           0.2069  ...        23.570          25.53           152.50   
3           0.2597  ...        14.910          26.50            98.87   
4           0.1809  ...        22.540          16.67           152.20   
..             ...  ...           ...            ...              ...   
564         0.1726  ...        25.450          26.40           166.10   
565         0.1752  ...        23.690          38.25           155.00   
566         0.1590  ...        18.980          34.12           126.70   
567         0.2397  ...        25.740          39.42           184.60   
568         0.1587  ...         9.456          30.37            59.16   

     area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0        2019.0           0.16220            0.66560           0.7119   
1        1956.0           0.12380            0.18660           0.2416   
2        1709.0           0.14440            0.42450           0.4504   
3         567.7           0.20980            0.86630           0.6869   
4        1575.0           0.13740            0.20500           0.4000   
..          ...               ...                ...              ...   
564      2027.0           0.14100            0.21130           0.4107   
565      1731.0           0.11660            0.19220           0.3215   
566      1124.0           0.11390            0.30940           0.3403   
567      1821.0           0.16500            0.86810           0.9387   
568       268.6           0.08996            0.06444           0.0000   

     concave points_worst  symmetry_worst  fractal_dimension_worst  
0                  0.2654          0.4601                  0.11890  
1                  0.1860          0.2750                  0.08902  
2                  0.2430          0.3613                  0.08758  
3                  0.2575          0.6638                  0.17300  
4                  0.1625          0.2364                  0.07678  
..                    ...         

In [81]:
data['diagnosis'].value_counts()

diagnosis
B    357
M    212
Name: count, dtype: int64

In [82]:
data.iloc[:, 0]

0      M
1      M
2      M
3      M
4      M
      ..
564    M
565    M
566    M
567    M
568    B
Name: diagnosis, Length: 569, dtype: object

In [83]:
X_train, X_test, y_train, y_test = train_test_split(data.iloc[:, 1:], data.iloc[:, 0], test_size=0.2)

In [84]:
X_train.head()

radius_mean  texture_mean  perimeter_mean  area_mean  smoothness_mean  \
281        11.74         14.02           74.24      427.3          0.07813   
137        11.43         15.39           73.06      399.8          0.09639   
464        13.17         18.22           84.28      537.3          0.07466   
475        12.83         15.73           82.89      506.9          0.09040   
15         14.54         27.54           96.73      658.8          0.11390   

     compactness_mean  concavity_mean  concave points_mean  symmetry_mean  \
281           0.04340         0.02245              0.02763         0.2101   
137           0.06889         0.03503              0.02875         0.1734   
464           0.05994         0.04859              0.02870         0.1454   
475           0.08269         0.05835              0.03078         0.1705   
15            0.15950         0.16390              0.07364         0.2303   

     fractal_dimension_mean  ...  radius_worst  texture_worst  \
281                 0.06113  ...         13.31          18.26   
137                 0.05865  ...         12.32          22.02   
464                 0.05549  ...         14.90          23.89   
475                 0.05913  ...         14.09          19.35   
15                  0.07077  ...         17.46          37.13   

     perimeter_worst  area_worst  smoothness_worst  compactness_worst  \
281            84.70       533.7            0.1036             0.0850   
137            79.93       462.0            0.1190             0.1648   
464            95.10       687.6            0.1282             0.1965   
475            93.22       605.8            0.1326             0.2610   
15            124.10       943.2            0.1678             0.6577   

     concavity_worst  concave points_worst  symmetry_worst  \
281          0.06735               0.08290          0.3101   
137          0.13990               0.08476          0.2676   
464          0.18760               0.10450          0.2235   
475          0.34760               0.09783          0.3006   
15           0.70260               0.17120          0.4218   

     fractal_dimension_worst  
281                  0.06688  
137                  0.06765  
464                  0.06925  
475                  0.07802  
15                   0.13410  

[5 rows x 30 columns]

In [85]:
scaler=StandardScaler()
X_train=scaler.fit_transform(X_train)
X_test=scaler.transform(X_test)

encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [86]:
X_train

array([[-0.68249372, -1.20485704, -0.73275081, ..., -0.50437629,
         0.32078092, -0.94017357],
       [-0.76824452, -0.88810098, -0.78000127, ..., -0.47640783,
        -0.36826878, -0.89807607],
       [-0.28693356, -0.23378005, -0.33072151, ..., -0.17958119,
        -1.08325917, -0.81060074],
       ...,
       [ 0.86931922,  0.88527057,  0.73922102, ..., -0.51264654,
        -0.7314385 , -1.03475628],
       [-1.02826309,  0.01361337, -1.00624286, ..., -1.26929884,
        -0.12507477, -0.46780678],
       [ 1.23168552, -0.48810974,  1.15566572, ...,  0.76623419,
        -0.01482682,  0.02642885]], shape=(455, 30))

In [87]:
X_test

array([[-0.28693356,  0.59625957, -0.28507276, ...,  0.66548756,
         1.28058661,  0.66171844],
       [-0.98123846, -0.94359109, -1.00303944, ..., -1.75092788,
        -0.3131448 , -1.22665529],
       [ 1.7793842 , -0.43493171,  1.69223869, ...,  1.42484648,
        -0.34719196, -0.73952703],
       ...,
       [-1.00613385,  0.22863756, -0.8965257 , ...,  0.45196485,
        -0.49635096,  1.96400745],
       [ 1.51383333,  0.56620242,  1.49602917, ...,  1.63987287,
         1.85128189, -0.26770696],
       [-0.48609672, -0.65226799, -0.38798266, ...,  0.26701208,
         0.53154906,  1.05645088]], shape=(114, 30))

In [88]:
y_train

array([0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0,
       1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1,
       0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1,
       0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0,
       0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0,
       1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1,
       1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0,
       1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0,
       0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0,
       1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0,

In [89]:
y_test

array([1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0,
       1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0,
       0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1,
       1, 0, 1, 0])

In [90]:
X_train_tensor = torch.from_numpy(X_train.astype(np.float32))
X_test_tensor = torch.from_numpy(X_test.astype(np.float32))
y_train_tensor = torch.from_numpy(y_train.astype(np.float32))
y_test_tensor = torch.from_numpy(y_test.astype(np.float32))

In [91]:
X_train_tensor.dtype

torch.float32

In [92]:
type(X_train_tensor)

torch.Tensor

In [93]:
class MySimpleNN(nn.Module):
    def __init__(self,new_features):
        super().__init__()
        self.linear1=nn.Linear(new_features,3)
        self.relu=nn.ReLU()
        self.linear2=nn.Linear(3,1)
        self.sigmoid=nn.Sigmoid()
    def forward(self,features):
        out=self.linear1(features)
        out=self.relu(out)
        out=self.linear2(out)
        out=self.sigmoid(out)
        return out

In [94]:
data.shape

(569, 31)

In [95]:
X_train.shape[1]

30

In [96]:
learning_rate=0.01
epochs=25

In [97]:
loss_fn = nn.BCELoss()

In [99]:
model = MySimpleNN(X_train.shape[1])

optimizer = torch.optim.SGD(model.parameters(), lr = learning_rate)

In [122]:
for epoch in range(100):
    #forward pass
    y_pred = model(X_train_tensor)

    #calculate loss after forward pass
    loss = loss_fn(y_pred, y_train_tensor.view(-1,1))

    #backpropogation after loss
    optimizer.zero_grad()

    loss.backward()

    #update params after gradient
    optimizer.step()

    #calculate loss
    print(f"epoch: {epoch+1}, Loss: {loss.item()}")

epoch: 1, Loss: 0.22376649081707
epoch: 2, Loss: 0.22322505712509155
epoch: 3, Loss: 0.22268575429916382
epoch: 4, Loss: 0.22214867174625397
epoch: 5, Loss: 0.22161374986171722
epoch: 6, Loss: 0.2210809737443924
epoch: 7, Loss: 0.22055035829544067
epoch: 8, Loss: 0.22002191841602325
epoch: 9, Loss: 0.21949563920497894
epoch: 10, Loss: 0.21897150576114655
epoch: 11, Loss: 0.21844950318336487
epoch: 12, Loss: 0.2179296612739563
epoch: 13, Loss: 0.21741196513175964
epoch: 14, Loss: 0.2168964147567749
epoch: 15, Loss: 0.2163829654455185
epoch: 16, Loss: 0.2158716320991516
epoch: 17, Loss: 0.21536244451999664
epoch: 18, Loss: 0.2148553878068924
epoch: 19, Loss: 0.21435043215751648
epoch: 20, Loss: 0.21384760737419128
epoch: 21, Loss: 0.21334683895111084
epoch: 22, Loss: 0.2128482162952423
epoch: 23, Loss: 0.21235166490077972
epoch: 24, Loss: 0.21185721457004547
epoch: 25, Loss: 0.21136482059955597
epoch: 26, Loss: 0.2108745574951172
epoch: 27, Loss: 0.21038632094860077
epoch: 28, Loss: 0.20

In [124]:
X_test_tensor.shape

torch.Size([114, 30])

In [125]:
X_test_tensor[1]

tensor([-0.9812, -0.9436, -1.0030, -0.8631, -0.6046, -1.1543, -1.1117, -1.2467,
         0.4053, -0.4248, -0.2885,  1.4567, -0.3657, -0.4094,  0.5229, -0.8861,
        -1.0496, -1.9275,  1.4409, -1.0565, -0.9757, -1.0387, -1.0087, -0.8242,
        -1.1123, -1.1916, -1.3097, -1.7509, -0.3131, -1.2267])

In [126]:
model.forward(X_test_tensor[1])

tensor([0.0419], grad_fn=<SigmoidBackward0>)

In [127]:
y_pred=model.forward(X_test_tensor[1])

In [128]:
y_pred

tensor([0.0419], grad_fn=<SigmoidBackward0>)

In [129]:
y_pred=(y_pred>0.5).float()

In [130]:
y_test_tensor=y_test_tensor[0]

IndexError: invalid index of a 0-dim tensor. Use `tensor.item()` in Python or `tensor.item<T>()` in C++ to convert a 0-dim tensor to a number

In [131]:
(y_pred==y_test_tensor).float()

tensor([0.])

In [132]:
with torch.no_grad():
    y_pred=model.forward(X_test_tensor)
    y_pred=(y_pred>0.5).float()
    accuracy = (y_pred == y_test_tensor).float().mean()
    print(f'Accuracy: {accuracy.item()}')

Accuracy: 0.2982456088066101


In [133]:
summary(model)

Layer (type:depth-idx)                   Param #
MySimpleNN                               --
├─Linear: 1-1                            93
├─ReLU: 1-2                              --
├─Linear: 1-3                            4
├─Sigmoid: 1-4                           --
Total params: 97
Trainable params: 97
Non-trainable params: 0

In [134]:
from sklearn.datasets import make_classification

In [135]:
# Step 1: Create a synthetic classification dataset using sklearn
X, y = make_classification(
    n_samples=10,       # Number of samples
    n_features=2,       # Number of features
    n_informative=2,    # Number of informative features
    n_redundant=0,      # Number of redundant features
    n_classes=2,        # Number of classes
    random_state=42     # For reproducibility
)

In [136]:
X

array([[ 1.06833894, -0.97007347],
       [-1.14021544, -0.83879234],
       [-2.8953973 ,  1.97686236],
       [-0.72063436, -0.96059253],
       [-1.96287438, -0.99225135],
       [-0.9382051 , -0.54304815],
       [ 1.72725924, -1.18582677],
       [ 1.77736657,  1.51157598],
       [ 1.89969252,  0.83444483],
       [-0.58723065, -1.97171753]])

In [137]:
y

array([1, 0, 0, 0, 0, 1, 1, 1, 1, 0])

In [138]:
# Convert the data to PyTorch tensors
X = torch.tensor(X, dtype=torch.float32)
y = torch.tensor(y, dtype=torch.long)

In [139]:
X

tensor([[ 1.0683, -0.9701],
        [-1.1402, -0.8388],
        [-2.8954,  1.9769],
        [-0.7206, -0.9606],
        [-1.9629, -0.9923],
        [-0.9382, -0.5430],
        [ 1.7273, -1.1858],
        [ 1.7774,  1.5116],
        [ 1.8997,  0.8344],
        [-0.5872, -1.9717]])

In [140]:
y

tensor([1, 0, 0, 0, 0, 1, 1, 1, 1, 0])

In [141]:
from torch.utils.data import Dataset, DataLoader

In [142]:
class CustomDataSet(Dataset):
    def __init__(self,features,labels):
        self.features=features
        self.labels=labels
        
    def __len__(self):
        return self.features.shape[0]
        
    def __getitem__(self,index):
        return self.features[index],self.labels[index]

In [143]:
dataset=CustomDataSet(X,y)

In [144]:
len(dataset)

10

In [145]:
dataset[2]

(tensor([-2.8954,  1.9769]), tensor(0))

In [146]:
dataset[9]

(tensor([-0.5872, -1.9717]), tensor(0))

In [150]:
dataloader=DataLoader(dataset,batch_size=2,shuffle=False)
dataloader

In [151]:
for batch_features, batch_labels in dataloader:

  print(batch_features)
  print(batch_labels)
  print("-"*50)

tensor([[ 1.0683, -0.9701],
        [-1.1402, -0.8388]])
tensor([1, 0])
--------------------------------------------------
tensor([[-2.8954,  1.9769],
        [-0.7206, -0.9606]])
tensor([0, 0])
--------------------------------------------------
tensor([[-1.9629, -0.9923],
        [-0.9382, -0.5430]])
tensor([0, 1])
--------------------------------------------------
tensor([[ 1.7273, -1.1858],
        [ 1.7774,  1.5116]])
tensor([1, 1])
--------------------------------------------------
tensor([[ 1.8997,  0.8344],
        [-0.5872, -1.9717]])
tensor([1, 0])
--------------------------------------------------
